index: /
patch: /patch/:version
perk: /perk/:id
perks:
  - /perks
  - /perks/:type
killer: /killer/:id
survivor: /survivor/:id
characters: /characters
data: /data
patchesFor: /patches/for/:id
addOn: /add-on/:id